/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function extractText(buf: Buffer): string
export declare function extractTextByPages(buf: Buffer): Array<string>
